name: .NET

on:
  workflow_dispatch: # manual trigger
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v5.8.2
      with:
        versionSpec: '5.5.0'
    
    - name: Calculate Build Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v5.8.2
      
    - name: Set VERSION
      run: |
        echo ${{ steps.gitversion.outputs.semVer }}.${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}-${{ steps.gitversion.outputs.ShortSha}}
        echo "VERSION=$(echo ${{ steps.gitversion.outputs.semVer }}.${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}-$(echo ${{ steps.gitversion.outputs.ShortSha}} | sed 's/^[0-9]*//))" >> $GITHUB_ENV
    
    - name: Print VERSION
      run: echo "VERSION - $VERSION"
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --no-build --verbosity normal Release /p:Version=${VERSION} --output
